<a href="https://colab.research.google.com/github/Sherilyn2/Programa-Python_Utec/blob/main/Sherilyn_Albornoz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Creación de listas (1 puntos)
Crea una lista llamada numeros_pares que contenga los números del 1 al 100
con saltos de 2 en 2.

numeros_pares = [2, 4, 6, 8, 10, 12 ... 100]

In [1]:
numeros_pares = list(range(2, 101, 2))
print(numeros_pares)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


2. Manipulación de listas (1 puntos)
Agrega los números 102, 104 y 106 al final de la lista numeros_pares y luego
elimina los primeros 5 números de la lista numeros_pares. Muestra la lista
resultante.

In [2]:
#Agregar 102, 104 y 106 al final

numeros_pares.extend([102, 104, 106])


#Eliminar los 5 primeros elementos
numeros_pares = numeros_pares[5:]
print(numeros_pares)


[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]


3. Operaciones con listas (2 puntos)
Crea una lista llamada resultante que contenga la raíz cuadrada de cada
elemento de la lista numeros_pares usando list comprehension.

In [3]:
resultante = [num ** 0.5 for num in numeros_pares]

print(resultante)

[3.4641016151377544, 3.7416573867739413, 4.0, 4.242640687119285, 4.47213595499958, 4.69041575982343, 4.898979485566356, 5.0990195135927845, 5.291502622129181, 5.477225575051661, 5.656854249492381, 5.830951894845301, 6.0, 6.164414002968976, 6.324555320336759, 6.48074069840786, 6.6332495807108, 6.782329983125268, 6.928203230275509, 7.0710678118654755, 7.211102550927978, 7.3484692283495345, 7.483314773547883, 7.615773105863909, 7.745966692414834, 7.874007874011811, 8.0, 8.12403840463596, 8.246211251235321, 8.366600265340756, 8.48528137423857, 8.602325267042627, 8.717797887081348, 8.831760866327848, 8.94427190999916, 9.055385138137417, 9.16515138991168, 9.273618495495704, 9.38083151964686, 9.486832980505138, 9.591663046625438, 9.695359714832659, 9.797958971132712, 9.899494936611665, 10.0, 10.099504938362077, 10.198039027185569, 10.295630140987]


4. Desempaquetado de tuplas (2 puntos)
Dada la siguiente tupla tupla_x = (“alumno”,”Pedro”,15), desempaqueta la
tupla tupla_x en tres variables: x, y, z, e imprime la siguiente estructura “El
alumno Pedro obtuvo la calificación de 15 usando las variables x, y, z”.

In [4]:
tupla_tupla=("alumno","Pedro",15)
x, y, z = tupla_tupla
print(f"El alumno {y} obtuvo la calificación de {z} usando las variables {x}, {y}, {z}.")

El alumno Pedro obtuvo la calificación de 15 usando las variables alumno, Pedro, 15.


5. Iteración en diccionarios (4 puntos)
Dado el siguiente diccionario notas = {“Programacion”:15.9,
“Matematica”: 15.1, “Fisica”:15.6}, escribe un bucle for que imprima
cada clave y su valor en el diccionario con la siguiente estructura “Mis
calificaciones en el curso de Programacion es 15.9”

In [5]:
notas={"Programacion":15.9, "Matematica": 15.1, "Fisica":15.6}

for clave, valor in notas.items():
    print(f"Mis calificaciones en el curso de {clave} es {valor}")

Mis calificaciones en el curso de Programacion es 15.9
Mis calificaciones en el curso de Matematica es 15.1
Mis calificaciones en el curso de Fisica es 15.6


6. Matrices y funciones de NumPy (4 puntos)
Crea una matriz 1D que contenga los primeros 16 elementos de la lista
numeros_pares (creada en la pregunta 1), modifique las dimensiones y
convertiela en una matriz 2D con shape(4,4), calcula la suma total de los
elementos de la matriz matriz 2D.

In [6]:

import numpy as np

#Lista de numeros pares del 2 al 100
numeros_pares = list(range(2, 101, 2))

#16 primeros elementos
primeros_16 = numeros_pares[:16]

#Matriz 1D
matriz_1D = np.array(primeros_16)

#Matriz 2D
matriz_2D = matriz_1D.reshape(4, 4)

#Suma total de los elementos
suma_total = np.sum(matriz_2D)

print("Matriz 2D:")
print(matriz_2D)
print(f"\nSuma total de los elementos: {suma_total}")

Matriz 2D:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Suma total de los elementos: 272


7. Pandas (6 puntos)
Leer el archivo datosDemograficos.xlsx y realice un análisis descriptivo en
función de las variables más relevantes.


In [9]:
import pandas as pd

df = pd.read_excel('datosDemograficos.xlsx')

print("Primeras filas del archivo:")
print(df.head())

estadisticas = df.describe()

estadisticas_clave = estadisticas.loc[['mean', 'min', 'max']]

estadisticas_clave = estadisticas_clave.T  # Transponer filas y columnas
estadisticas_clave.columns = ['Media', 'Mínimo', 'Máximo']

print("\n Estadísticas clave por variable:")
print(estadisticas_clave)

Primeras filas del archivo:
  Indicadores  Fecundidad  Mortalidad  TasaMortalidadxMil  EsperanzaVida  \
0        Puno       30108        9951                6.86          71.44   
1  San Martín       16074        4889                5.63          72.45   
2       Tacna        5605        1900                5.40          75.11   
3      Tumbes        3924        1209                4.94          74.96   
4     Ucayali        8872        3020                5.93          71.99   

   EVSoloHombres  EVSoloMujeres  TasaMortalidadInfantilxMilNacidos  \
0          68.77          74.25                              26.82   
1          69.65          75.40                              17.53   
2          72.31          78.06                              11.77   
3          72.09          77.98                              11.46   
4          69.24          74.87                              21.07   

   CrecimientoNatural  
0               20157  
1               11185  
2                3705 